# Multi-stage Docker build for Iris Classification ML Application

# Stage 1: Base image with Python
FROM python:3.12-slim as base

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Stage 2: Dependencies
FROM base as dependencies

# Copy dependency files
COPY pyproject.toml ./

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -e .

# Stage 3: Application
FROM dependencies as application

# Copy application code
COPY config/ ./config/
COPY src/ ./src/
COPY app.py ./
COPY train.py ./

# Create necessary directories
RUN mkdir -p models data logs plots

# Copy pre-trained model artifacts if they exist
# (These should be generated by running train.py first)
COPY models/ ./models/ 2>/dev/null || true

# Expose Gradio port
EXPOSE 7860

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD python -c "import requests; requests.get('http://localhost:7860')" || exit 1

# Run Gradio application
CMD ["python", "app.py"]
